FORMAT: 1A
HOST: http://agenda12.apiblueprint.org/

# Agenda

Agenda is a simple API allowing consumers to schedule meeting on-line



# Group User

Resources related to a users in the API.

## Users [/v1/user/users{?key}]

+ Parameters
    - key : `1e3576bt` (string, required)

### Get all Users [GET]

+ Response 200 (application/json)

        [
            {
                "username":"zhang3"
                "password":"zhang"
                "email":"zhang3@mail2.sysu.edu.cn"
                "phone":"123123"
            },{
                "username":"li4"
                "password":"li"
                "email":"li4@mail2.sysu.edu.cn"
                "phone":"456456"
            }
        ]

### Resigter a New User [POST]

+ Request (application/json)

        {
            "username":"zhang3"
            "password":"zhang"
            "email":"zhang3@mail2.sysu.edu.cn"
            "phone":"123123"
        }

+ Response 201 (application/json)

    + Headers

            Location: /user/users/zhang3

    + Body

            {
                "username":"zhang3"
                "password":"zhang"
                "email":"zhang3@mail2.sysu.edu.cn"
                "phone":"123123"
            }
            
### Delete User [DELETE /v1/user/users/{username}]

+ Parameters
    - username : `root` (string, required) - User Name
    
+ Response 204
            

## Login [/v1/user/login{?username,password}]

+ Parameters
    - username : `root` (string, required) - User Name
    - password : `pass` (required)
    
### Verify Login [GET]

+ Response 200 (application/json)

        {
            "result": 1
        }
        


# Group Meetings

## New Meeting [/v1/meeting/NewMeeting]

### Create Meeting [POST]


+ Request (application/json)

        {
            "title":"yup"
            "participants":"zhang"
            "start_time":"1111"
            "end_time":"22222"
        }

+ Response 201 (application/json)

    + Headers

            Location: /meeting/NewMeeting/yup

    + Body

            {
            "title":"yup"
            "participants":"zhang"
            "start_time":"1111"
            "end_time":"22222"
            }